apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-arm
spec:
  template:
    spec:
      containers:
      - name: podtato-head-left-arm
        image: ghcr.io/podtato-head/left-arm:0.2.1
