apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
spec:
  template:
    spec:
      containers:
        - name: podtato-head-hat
          env:
          - name: PODTATO_PART_NUMBER
            value: "02"
