---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-entry
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: entry
    app.kubernetes.io/version: '0.2.7'
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: entry
