apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "terraform"
spec:
  stages:
    - name: "test"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "deployment"
        - name: "release"
​
    - name: "uat"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "test.delivery.finished"
        tasks: 
        - name: "deployment"
        - name: "release"
​
    - name: "prod"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "uat.delivery.finished"
        tasks: 
        - name: "deployment"
        - name: "release"
