apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  accounts.keptn: $keptn.apiToken
  url: https://argocd.bradmccoy.io
  kustomize.buildOptions: --enable-helm
  ga.trackingid: "G-SMLWM11VB0"
  repositories: |
    - url: https://github.com/ortelius/ortelius-kubernetes.git
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
